apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-manager
  namespace: fin-man
  labels:
    app: finman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finman
  template:
    metadata:
      labels:
        app: finman
    spec:
      containers:
      - name: finman
        image: dockerfonseka/fin-man:0.1
        env:
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: fin-man-secret
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fin-man-secret
              key: PG_PASSWORD
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: fin-man-secret
              key: PG_HOST
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: fin-man-secret
              key: PG_PORT
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: fin-man-secret
              key: PG_DB
        ports:
        - containerPort: 8080